### ISSUE TITLE
Device 'reset'

### ISSUE THREAD

**Issue by haivala** [rsc-dev/loophole#6]
What files do I have to delete from the device to get it working again?
I deleted every file with date on it but it still says "please sync".

I would like to use only this software to get it working because I only have linux and I don't want it to connect to Internet. My computer should be enough.

**Comment by rsc-dev** [comment]
It is not so easy. FlowSync is modifing some system files after sync. The easiest way to check it is to dump device memory befora and after sync. This is a nice goal anyway.

**Comment by haivala** [comment]
Yeah I thought about the same thing so I asked first if someone had done it already..

**Comment by haivala** [comment]
Well I just have to wait if someone cracks this one. I don't have time, windows or mac to play with..

**Comment by haivala** [comment]
could somebody at least give the diffs?

**Comment by fernsehkind** [comment]
I can't give you the diffs, because they contain personal data but here some information which files are changed after a sync:
- JOURNAL.DAT changed
- SYNCINFO.BPB changed
- U/0/DBDC.DAT changed
- U/0/YYYYMMDD/PHYSDATA/ deleted (old data not from the day of the sync)
- U/0/YYYYMMDD/ACT/ID.BPB created (old data not from the day of the sync)
- U/0/S/PHYSDATA.BPB changed
- U/0/S/UDEVSET.BPB changed
- U/0/TL/RECOVS.BPB changed

I use loophole in https://github.com/fernsehkind/PALOR and the only feature missing is the delete/remove old data feature. So I'm highly interested to include this feature, too. Give me some time to investigate.

**Comment by rsc-dev** [comment]
Resolved. Delete is now supported. Also please take a look at: https://github.com/rsc-dev/A360
